// Mock Brokers Data
export const mockBrokers = [
    {
        id: "broker-1",
        name: "Rajesh Kumar",
        email: "rajesh@realestate.com",
        phone: "9876543210",
        address: "123 Main Street",
        city: "Mumbai",
        area: "Andheri",
        status: "approved",
        subscriptionPlan: "Premium",
        subscriptionStatus: "active",
        createdAt: "2024-01-15",
        totalProperties: 45,
        totalLeads: 120,
    },
    {
        id: "broker-2",
        name: "Priya Sharma",
        email: "priya@homefinders.com",
        phone: "9876543211",
        address: "456 Park Avenue",
        city: "Delhi",
        area: "Gurgaon",
        status: "approved",
        subscriptionPlan: "Basic",
        subscriptionStatus: "active",
        createdAt: "2024-02-20",
        totalProperties: 23,
        totalLeads: 67,
    },
    {
        id: "broker-3",
        name: "Amit Patel",
        email: "amit@propertyworld.com",
        phone: "9876543212",
        address: "789 Business Hub",
        city: "Ahmedabad",
        area: "Navrangpura",
        status: "pending",
        createdAt: "2024-03-10",
        totalProperties: 0,
        totalLeads: 0,
    },
    {
        id: "broker-4",
        name: "Sunita Reddy",
        email: "sunita@dreamhomes.com",
        phone: "9876543213",
        address: "321 Lake View",
        city: "Hyderabad",
        area: "Secunderabad",
        status: "approved",
        subscriptionPlan: "Enterprise",
        subscriptionStatus: "active",
        createdAt: "2024-01-05",
        totalProperties: 78,
        totalLeads: 234,
    },
    {
        id: "broker-5",
        name: "Vikram Singh",
        email: "vikram@estates.com",
        phone: "9876543214",
        address: "567 Green Valley",
        city: "Jaipur",
        area: "Sanganer",
        status: "suspended",
        subscriptionPlan: "Basic",
        subscriptionStatus: "inactive",
        createdAt: "2024-02-01",
        totalProperties: 12,
        totalLeads: 34,
    },
];
// Mock Customers Data
export const mockCustomers = [
    {
        id: "customer-1",
        name: "Arun Mehta",
        email: "arun@email.com",
        phone: "9123456780",
        preferences: {
            propertyType: ["apartment", "villa"],
            budgetMin: 5000000,
            budgetMax: 15000000,
            locations: ["Mumbai", "Pune"],
        },
        savedProperties: ["prop-1", "prop-3"],
        inquiries: 8,
        status: "active",
        createdAt: "2024-03-01",
    },
    {
        id: "customer-2",
        name: "Meera Joshi",
        email: "meera@email.com",
        phone: "9123456781",
        preferences: {
            propertyType: ["house"],
            budgetMin: 10000000,
            budgetMax: 25000000,
            locations: ["Delhi", "Gurgaon"],
        },
        savedProperties: ["prop-2"],
        inquiries: 5,
        status: "active",
        createdAt: "2024-02-15",
    },
    {
        id: "customer-3",
        name: "Karan Malhotra",
        email: "karan@email.com",
        phone: "9123456782",
        preferences: {
            propertyType: ["commercial", "office"],
            budgetMin: 20000000,
            budgetMax: 50000000,
            locations: ["Bangalore"],
        },
        savedProperties: [],
        inquiries: 12,
        status: "active",
        createdAt: "2024-01-20",
    },
    {
        id: "customer-4",
        name: "Neha Kapoor",
        email: "neha@email.com",
        phone: "9123456783",
        savedProperties: ["prop-1", "prop-4", "prop-5"],
        inquiries: 3,
        status: "inactive",
        createdAt: "2024-03-05",
    },
];
// Mock Properties Data
export const mockProperties = [
    {
        id: "prop-1",
        title: "Luxury 3BHK Apartment in Bandra",
        description: "Stunning sea-facing apartment with modern amenities and premium finishes. Located in the heart of Bandra with easy access to all facilities.",
        propertyType: "apartment",
        transactionType: "sale",
        price: 25000000,
        area: 1800,
        areaUnit: "sqft",
        bedrooms: 3,
        bathrooms: 3,
        address: "Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400050",
        images: [],
        amenities: ["Swimming Pool", "Gym", "Parking", "Security", "Garden"],
        brokerId: "broker-1",
        brokerName: "Rajesh Kumar",
        status: "active",
        featured: true,
        views: 1250,
        inquiries: 45,
        createdAt: "2024-03-01",
    },
    {
        id: "prop-2",
        title: "Modern Villa with Garden in Gurgaon",
        description: "Spacious 4BHK independent villa with private garden, rooftop terrace, and smart home features. Perfect for families.",
        propertyType: "villa",
        transactionType: "sale",
        price: 45000000,
        area: 3500,
        areaUnit: "sqft",
        bedrooms: 4,
        bathrooms: 4,
        address: "DLF Phase 5",
        city: "Gurgaon",
        state: "Haryana",
        pincode: "122001",
        images: [],
        amenities: ["Garden", "Rooftop", "Smart Home", "Parking", "Modular Kitchen"],
        brokerId: "broker-2",
        brokerName: "Priya Sharma",
        status: "active",
        featured: true,
        views: 890,
        inquiries: 32,
        createdAt: "2024-02-20",
    },
    {
        id: "prop-3",
        title: "Commercial Office Space in BKC",
        description: "Prime commercial office space in Bandra Kurla Complex. Ideal for startups and corporate offices. Fully furnished with AC.",
        propertyType: "office",
        transactionType: "rent",
        price: 150000,
        area: 2500,
        areaUnit: "sqft",
        address: "BKC",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400051",
        images: [],
        amenities: ["AC", "Parking", "Cafeteria", "Conference Room", "24x7 Security"],
        brokerId: "broker-4",
        brokerName: "Sunita Reddy",
        status: "active",
        featured: false,
        views: 560,
        inquiries: 18,
        createdAt: "2024-03-10",
    },
    {
        id: "prop-4",
        title: "Budget 2BHK in Andheri",
        description: "Well-maintained 2BHK apartment in Andheri East. Close to metro station and shopping areas. Ready to move.",
        propertyType: "apartment",
        transactionType: "sale",
        price: 8500000,
        area: 850,
        areaUnit: "sqft",
        bedrooms: 2,
        bathrooms: 2,
        address: "Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400069",
        images: [],
        amenities: ["Parking", "Security", "Power Backup"],
        brokerId: "broker-1",
        brokerName: "Rajesh Kumar",
        status: "pending",
        featured: false,
        views: 340,
        inquiries: 12,
        createdAt: "2024-03-15",
    },
    {
        id: "prop-5",
        title: "Premium Plot in Whitefield",
        description: "Residential plot in a gated community. Clear title, all approvals in place. Excellent investment opportunity.",
        propertyType: "plot",
        transactionType: "sale",
        price: 12000000,
        area: 2400,
        areaUnit: "sqft",
        address: "Whitefield",
        city: "Bangalore",
        state: "Karnataka",
        pincode: "560066",
        images: [],
        amenities: ["Gated Community", "Underground Cabling", "Park"],
        brokerId: "broker-4",
        brokerName: "Sunita Reddy",
        status: "active",
        featured: false,
        views: 210,
        inquiries: 8,
        createdAt: "2024-03-05",
    },
];
// Mock Plans Data
export const mockPlans = [
    {
        id: "plan-1",
        name: "Basic",
        description: "Perfect for individual brokers starting out",
        price: 999,
        duration: 1,
        durationUnit: "months",
        features: ["Up to 10 property listings", "Basic analytics", "Email support", "Standard visibility"],
        maxProperties: 10,
        maxLeads: 50,
        featuredListings: 0,
        prioritySupport: false,
        analyticsAccess: false,
        status: "active",
        createdAt: "2024-01-01",
    },
    {
        id: "plan-2",
        name: "Premium",
        description: "Ideal for growing real estate businesses",
        price: 2499,
        duration: 1,
        durationUnit: "months",
        features: ["Up to 50 property listings", "Advanced analytics", "Priority support", "Featured listings", "Lead management"],
        maxProperties: 50,
        maxLeads: 200,
        featuredListings: 5,
        prioritySupport: true,
        analyticsAccess: true,
        status: "active",
        createdAt: "2024-01-01",
    },
    {
        id: "plan-3",
        name: "Enterprise",
        description: "For large agencies and property developers",
        price: 4999,
        duration: 1,
        durationUnit: "months",
        features: ["Unlimited property listings", "Full analytics suite", "Dedicated account manager", "Premium visibility", "API access", "Custom branding"],
        maxProperties: 999,
        maxLeads: 999,
        featuredListings: 20,
        prioritySupport: true,
        analyticsAccess: true,
        status: "active",
        createdAt: "2024-01-01",
    },
];
// Mock Notifications Data
export const mockNotifications = [
    {
        id: "notif-1",
        title: "New Feature: Virtual Property Tours",
        message: "We are excited to announce virtual property tours are now available for all premium members. Showcase your properties in 360 degrees!",
        status: "sent",
        sentAt: "2024-03-15",
        createdAt: "2024-03-14",
    },
    {
        id: "notif-2",
        title: "Maintenance Scheduled",
        message: "The platform will undergo scheduled maintenance on March 20th from 2 AM to 4 AM IST. We apologize for any inconvenience.",
        status: "scheduled",
        scheduledAt: "2024-03-20",
        createdAt: "2024-03-16",
    },
    {
        id: "notif-3",
        title: "Special Offer: 20% Off Premium Plans",
        message: "Upgrade to Premium and get 20% off for the first 3 months. Use code PREMIUM20 at checkout. Offer valid till March 31st.",
        status: "sent",
        sentAt: "2024-03-10",
        createdAt: "2024-03-09",
    },
];
// Dashboard Statistics
export const dashboardStats = {
    totalBrokers: 156,
    activeBrokers: 142,
    pendingApprovals: 8,
    totalCustomers: 2345,
    activeCustomers: 1890,
    totalProperties: 4567,
    activeListings: 3890,
    pendingListings: 234,
    totalRevenue: 1234567,
    monthlyRevenue: 234567,
    totalSubscriptions: 142,
    expiringSubscriptions: 12,
};
// Revenue Data for Charts
export const revenueData = [
    { month: "Jan", revenue: 180000, subscriptions: 45 },
    { month: "Feb", revenue: 195000, subscriptions: 52 },
    { month: "Mar", revenue: 220000, subscriptions: 58 },
    { month: "Apr", revenue: 205000, subscriptions: 55 },
    { month: "May", revenue: 235000, subscriptions: 62 },
    { month: "Jun", revenue: 250000, subscriptions: 68 },
];
// Property Type Distribution
export const propertyTypeData = [
    { type: "Apartment", count: 1890, percentage: 41 },
    { type: "House", count: 920, percentage: 20 },
    { type: "Villa", count: 460, percentage: 10 },
    { type: "Plot", count: 690, percentage: 15 },
    { type: "Commercial", count: 460, percentage: 10 },
    { type: "Office", count: 147, percentage: 4 },
];
// Location Distribution
export const locationData = [
    { city: "Mumbai", properties: 1250, brokers: 45 },
    { city: "Delhi", properties: 890, brokers: 32 },
    { city: "Bangalore", properties: 780, brokers: 28 },
    { city: "Hyderabad", properties: 560, brokers: 22 },
    { city: "Chennai", properties: 450, brokers: 18 },
    { city: "Pune", properties: 340, brokers: 15 },
];
